package jogodavelha;

import javax.swing.JOptionPane;

public class JFrameJogo extends javax.swing.JFrame {
    Velha tab;
    Jogador jogador;
    int c;
    
    public JFrameJogo() {
        tab = new Velha();
        c = -1;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        posicaoA1 = new javax.swing.JButton();
        posicaoA2 = new javax.swing.JButton();
        posicaoA3 = new javax.swing.JButton();
        posicaoB1 = new javax.swing.JButton();
        posicaoB2 = new javax.swing.JButton();
        posicaoB3 = new javax.swing.JButton();
        posicaoC1 = new javax.swing.JButton();
        posicaoC2 = new javax.swing.JButton();
        posicaoC3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomeJogador1 = new javax.swing.JTextField();
        nomeJogador2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        simboloJogador1 = new javax.swing.JTextField();
        simboloJogador2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setEnabled(false);

        posicaoA1.setEnabled(false);
        posicaoA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicaoA1ActionPerformed(evt);
            }
        });

        posicaoA2.setEnabled(false);
        posicaoA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicaoA2ActionPerformed(evt);
            }
        });

        posicaoA3.setEnabled(false);
        posicaoA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicaoA3ActionPerformed(evt);
            }
        });

        posicaoB1.setEnabled(false);
        posicaoB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicaoB1ActionPerformed(evt);
            }
        });

        posicaoB2.setEnabled(false);
        posicaoB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicaoB2ActionPerformed(evt);
            }
        });

        posicaoB3.setEnabled(false);
        posicaoB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicaoB3ActionPerformed(evt);
            }
        });

        posicaoC1.setEnabled(false);
        posicaoC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicaoC1ActionPerformed(evt);
            }
        });

        posicaoC2.setEnabled(false);
        posicaoC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicaoC2ActionPerformed(evt);
            }
        });

        posicaoC3.setEnabled(false);
        posicaoC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicaoC3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Jogador 1:");

        jLabel2.setText("Jogador 2:");

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Simbolo");

        jLabel4.setText("Simbolo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(posicaoC1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(posicaoC2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(posicaoC3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(posicaoB1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(posicaoB2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(posicaoB3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(posicaoA1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(posicaoA2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(posicaoA3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nomeJogador1)
                            .addComponent(nomeJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(simboloJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(simboloJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simboloJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomeJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simboloJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(posicaoA2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(posicaoA1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(posicaoA3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(posicaoB3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(posicaoB2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(posicaoB1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(posicaoC3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(posicaoC2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(posicaoC1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        tab.setJogador1(criaJogador(1));
        tab.setJogador2(criaJogador(2));
        if (tab.verificaSimbolo(tab.getJogador1().getSimbolo(), tab.getJogador2().getSimbolo()))
            JOptionPane.showMessageDialog(null, "Simbolos iguais, mude o simbolo de algum jogador e se inscreva novamente");
        else {
            mudaBloqueio(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void posicaoA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicaoA1ActionPerformed
        c++;
        if(quemVaiJogar(c)) {
            tab.a1 = tab.getJogador1().getSimbolo();
        } else {
            tab.a1 = tab.getJogador2().getSimbolo();
        }
        proximoPasso();
    }//GEN-LAST:event_posicaoA1ActionPerformed

    private void posicaoA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicaoA2ActionPerformed
        c++;
        if(quemVaiJogar(c)) {
            tab.a2 = tab.getJogador1().getSimbolo();
        } else {
            tab.a2 = tab.getJogador2().getSimbolo();
        }
        proximoPasso();
    }//GEN-LAST:event_posicaoA2ActionPerformed

    private void posicaoA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicaoA3ActionPerformed
        c++;
        if(quemVaiJogar(c)) {
            tab.a3 = tab.getJogador1().getSimbolo();
        } else {
            tab.a3 = tab.getJogador2().getSimbolo();
        }
        proximoPasso();
    }//GEN-LAST:event_posicaoA3ActionPerformed

    private void posicaoB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicaoB1ActionPerformed
        c++;
        if(quemVaiJogar(c)) {
            tab.b1 = tab.getJogador1().getSimbolo();
        } else {
            tab.b1 = tab.getJogador2().getSimbolo();
        }
        proximoPasso();
    }//GEN-LAST:event_posicaoB1ActionPerformed

    private void posicaoB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicaoB2ActionPerformed
        c++;
        if(quemVaiJogar(c)) {
            tab.b2 = tab.getJogador1().getSimbolo();
        } else {
            tab.b2 = tab.getJogador2().getSimbolo();
        }
        proximoPasso();
    }//GEN-LAST:event_posicaoB2ActionPerformed

    private void posicaoB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicaoB3ActionPerformed
        c++;
        if(quemVaiJogar(c)) {
            tab.b3 = tab.getJogador1().getSimbolo();
        } else {
            tab.b3 = tab.getJogador2().getSimbolo();
        }
        proximoPasso();
    }//GEN-LAST:event_posicaoB3ActionPerformed

    private void posicaoC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicaoC1ActionPerformed
        c++;
        if(quemVaiJogar(c)) {
            tab.c1 = tab.getJogador1().getSimbolo();
        } else {
            tab.c1 = tab.getJogador2().getSimbolo();
        }
        proximoPasso();
    }//GEN-LAST:event_posicaoC1ActionPerformed

    private void posicaoC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicaoC2ActionPerformed
        c++;
        if(quemVaiJogar(c)) {
            tab.c2 = tab.getJogador1().getSimbolo();
        } else {
            tab.c2 = tab.getJogador2().getSimbolo();
        }
        proximoPasso();
    }//GEN-LAST:event_posicaoC2ActionPerformed

    private void posicaoC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicaoC3ActionPerformed
        c++;
        if(quemVaiJogar(c)) {
            tab.c3 = tab.getJogador1().getSimbolo();
        } else {
            tab.c3 = tab.getJogador2().getSimbolo();
        }
        proximoPasso();
    }//GEN-LAST:event_posicaoC3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeJogador1;
    private javax.swing.JTextField nomeJogador2;
    private javax.swing.JButton posicaoA1;
    private javax.swing.JButton posicaoA2;
    private javax.swing.JButton posicaoA3;
    private javax.swing.JButton posicaoB1;
    private javax.swing.JButton posicaoB2;
    private javax.swing.JButton posicaoB3;
    private javax.swing.JButton posicaoC1;
    private javax.swing.JButton posicaoC2;
    private javax.swing.JButton posicaoC3;
    private javax.swing.JTextField simboloJogador1;
    private javax.swing.JTextField simboloJogador2;
    // End of variables declaration//GEN-END:variables
    private boolean quemVaiJogar(int contador) {
        return contador % 2 == 0;
    }

    private Jogador criaJogador(int qualJogador) {
        jogador = new Jogador();
        if (qualJogador == 1) {
            jogador.setNome(nomeJogador1.getText());
            jogador.setSimbolo(simboloJogador1.getText().charAt(0));   
        } else if (qualJogador == 2) {
            jogador.setNome(nomeJogador2.getText());
            jogador.setSimbolo(simboloJogador2.getText().charAt(0));
        }
        return jogador;
    }
    
    private void mudaBloqueio(boolean i) {
        //bloqueia para o usuário não se inscrever mais e libera o jogo
        nomeJogador1.setEnabled(i);
        nomeJogador2.setEnabled(i);
        simboloJogador1.setEnabled(i);
        simboloJogador2.setEnabled(i);
        jButton1.setEnabled(i);
        posicaoA1.setEnabled(!i);
        posicaoA2.setEnabled(!i);
        posicaoA3.setEnabled(!i);
        posicaoB1.setEnabled(!i);
        posicaoB2.setEnabled(!i);
        posicaoB3.setEnabled(!i);
        posicaoC1.setEnabled(!i);
        posicaoC2.setEnabled(!i);
        posicaoC3.setEnabled(!i);
    }

    private void proximoPasso(){
        desenhaBotoes();
        if(tab.verificaJogo() == "Vencedor !"){
            JOptionPane.showMessageDialog(null, tab.verificaJogo());
            tab.reiniciar();
        }
    }
    
    private void desenhaBotoes(){
        posicaoA1.setText(String.valueOf(tab.a1));
        posicaoA2.setText(String.valueOf(tab.a2));
        posicaoA3.setText(String.valueOf(tab.a3));
        posicaoB1.setText(String.valueOf(tab.b1));
        posicaoB2.setText(String.valueOf(tab.b2));
        posicaoB3.setText(String.valueOf(tab.b3));
        posicaoC1.setText(String.valueOf(tab.c1));
        posicaoC2.setText(String.valueOf(tab.c2));
        posicaoC3.setText(String.valueOf(tab.c3));
    }
    
}
